# Service Account Key authentication method
# See Authentication methods below for more config options
data_source soda_ci_cd:
  type: bigquery
  account_info_json: ${ GCP_SA_KEY }
  auth_scopes:
  - https://www.googleapis.com/auth/bigquery
  - https://www.googleapis.com/auth/cloud-platform
  - https://www.googleapis.com/auth/drive
  project_id: "dbt-ci-cd"
  dataset: dbt_soda_dataset

soda_cloud:
  host: cloud.soda.io
  api_key_id: ${ SODA_API_KEY_ID }
  api_key_secret: ${ SODA_API_KEY_SECRET }