dbt_soda_project:
  outputs:
    dev:
      dataset: dbt_soda_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: dbt-ci-cd
      threads: 2
      type: bigquery
      impersonate_service_account: dbt-runner@dbt-ci-cd.iam.gserviceaccount.com
  target: dev