name: Upload CSV to Google Cloud Storage

on:
  push:
    branches:
      - main
    paths:
      - 'sample_data.csv'

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Upload file to Google Cloud Storage
      run: gsutil cp ./sample_data.csv gs://dbt-soda-ci-cd
