name: Upload CSV to Google Cloud Storage

on:
  push:
    branches:
      - main
    paths:
      - 'sample_data/**'

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'sample_data'
        destination: ${{ secrets.GCS_LOCATION }} 

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Create BigQuery External Table
      run: |
        bq mk \
        --external_table_definition=CSV:sample_data.json@gs://dbt-soda-ci-cd/sample_data/sample_data.csv \
        dbt-ci-cd:external_tables.employees

