name: Upload CSV to Google Cloud Storage

on:
  push:
    branches:
      - main
    paths:
      - 'sample_data.csv'

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: $GCP_SA_KEY


    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'sample_data.csv'
        destination: 'dbt-soda-ci-cd'
