name: upload sample_data.csv to gcs, run dbt, and checks in soda

on:
  push:
    branches:
      - main
    paths:
      - 'sample_data/**'
      - 'dbt_soda_project/**'
      - 'soda/**'
  pull_request:
    branches:
      - main
    paths:
      - 'sample_data/**'
      - 'dbt_soda_project/**'
      - 'soda/**'
      
jobs:
  run-dbt-with-soda-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@main

    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' 

    - name: install poetry and soda
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        pip install -i https://pypi.cloud.soda.io soda-bigquery==1.0.4

    - name: authenticate to google cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_JSON }}

    - name: upload to google cloud storage
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: 'sample_data'
        destination: ${{ secrets.GCS_LOCATION }}

    - name: install poetry dependencies
      run: |
        poetry install

    - name: run poetry variables and installing dbt dependencies
      working-directory: ./dbt_soda_project
      run: |
        poetry run dbt deps

    - name: run dbt
      working-directory: ./
      env:
         DATASET: ${{ secrets.DATASET }}
         PROJECT_ID: ${{ secrets.PROJECT_ID }}
      run: |
        poetry run dbt run --project-dir dbt_soda_project/ --profiles-dir dbt_soda_project/

    - name: perform soda scan
      uses: sodadata/soda-github-action@main
      env:
         GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
         PROJECT_ID_WITH_QUOTES: ${{ secrets.PROJECT_ID_WITH_QUOTES }}
         DATASET: ${{ secrets.DATASET }}
         SODA_API_KEY_ID: ${{ secrets.SODA_API_KEY_ID }}
         SODA_API_KEY_SECRET: ${{ secrets.SODA_API_KEY_SECRET }}
      with:
        soda_library_version: v1.0.4
        data_source: soda_ci_cd
        configuration: ./soda/configuration.yml
        checks: ./soda/checks.yml

